
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VirtualHIE.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class Hospital
{

    public Hospital()
    {

        this.PatientDataAccesses = new HashSet<PatientDataAccess>();

        this.PatientDataRequests = new HashSet<PatientDataRequest>();

        this.PatientTreatmentDetails = new HashSet<PatientTreatmentDetail>();

    }


    public int Id { get; set; }

    [Display(Name = "Hospital Name")]
    public string HospitalName { get; set; }

    public string Address { get; set; }
   
    [Display(Name = "Region")]
    public int StateId { get; set; }

    [Display(Name = "User Id")]
    public int UserId { get; set; }

    [Display(Name = "Enrollment Status")]
    public int EnrollmentStatus { get; set; }

    [Display(Name = "Phone Number")]
    public string PhoneNumber { get; set; }

    [Display(Name = "Email Id")]
    public string EmailId { get; set; }



    public virtual EnrollmentStatu EnrollmentStatu { get; set; }

    public virtual State State { get; set; }

    public virtual User User { get; set; }

    public virtual ICollection<PatientDataAccess> PatientDataAccesses { get; set; }

    public virtual ICollection<PatientDataRequest> PatientDataRequests { get; set; }

    public virtual ICollection<PatientTreatmentDetail> PatientTreatmentDetails { get; set; }

}

}
