//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualHIE.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Hospitals = new HashSet<Hospital>();
        }
    
        public int id { get; set; }
        [Display(Name = "User ID")]
        public string UserId { get; set; }
    
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Hospital> Hospitals { get; set; }
        public virtual Role Role { get; set; }
    }
}
